version: '3'
services:
  rest:
    # Check https://gitlab.com/debuglevel/omnitracker-git/container_registry for stable image URLs (if you do not want to use "latest" but a certain version)
    image: registry.gitlab.com/debuglevel/omnitracker-git:latest
    ports:
      - "80:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      - APP_OMNITRACKERGIT_DATABASE_CONNECTIONSTRING=jdbc:sqlserver://myhost\\MYINSTANCE;databaseName=mydatabase;user=myuser;password=mypassword
      #- APP_OMNITRACKERGIT_DATABASE_CONNECTIONSTRING=jdbc:ucanaccess://OT-Templates.mdb
      - APP_OMNITRACKERGIT_GIT_REPOSITORY_URI=http://mygit/myrepo
      - APP_OMNITRACKERGIT_GIT_REPOSITORY_USER=myUser
      - APP_OMNITRACKERGIT_GIT_REPOSITORY_PASSWORD=myPassword
      - APP_OMNITRACKERGIT_SCHEDULED_COMMITS_ENABLED=true
      - APP_OMNITRACKERGIT_SCHEDULED_COMMITS_INTERVAL=60s
