version: '3'
services:
  omnitracker-git:
    # Check https://gitlab.com/debuglevel/omnitracker-git/container_registry for stable image URLs (if you do not want to use "latest" but a certain version)
    image: registry.gitlab.com/debuglevel/omnitracker-git:latest
    environment:
      - DAEMON=yes
      - SLEEP_DURATION=60
      - DATABASE_CONNECTION_STRING=jdbc:sqlserver://myhost\\MYINSTANCE;databaseName=mydatabase;user=myuser;password=mypassword
      - GIT_REPOSITORY_URI=http://mygit/myrepo
      - GIT_USER=myUser
      - GIT_PASSWORD=myPassword

#version: '3'
#services:
  rest:
    build: .
    image: omnitracker-git
    ports:
      - "80:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
#      # enable health check if Consul is used
#      - CONSUL_CLIENT_HEALTH_CHECK=true
#      # register this service on Consul
#      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
#      # search for services on Consul
#      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
#      # Consul server
#      - CONSUL_HOST=localhost
#      - CONSUL_PORT=8500